# Generated by Django 5.2.8 on 2025-11-16 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BandMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g., Electric Guitar, Drums, Singer', max_length=200)),
                ('instagram_handle', models.CharField(blank=True, help_text='Without @ symbol', max_length=100, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('ticket_url', models.URLField(blank=True, null=True)),
                ('is_upcoming', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_type', models.CharField(choices=[('EP', 'EP'), ('Single', 'Single'), ('Album', 'Album')], max_length=20)),
                ('release_date', models.DateField()),
                ('spotify_url', models.URLField()),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('artwork_url', models.URLField(blank=True, help_text='URL to artwork image', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (newest first)')),
            ],
            options={
                'ordering': ['-order', '-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('spotify_url', models.URLField()),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('track_number', models.IntegerField(default=1)),
                ('duration', models.CharField(blank=True, help_text='e.g., 4:10', max_length=20)),
                ('streams', models.IntegerField(default=0, help_text='Stream count')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='base.release')),
            ],
            options={
                'ordering': ['release', 'track_number'],
            },
        ),
    ]
