# Generated by Django 5.2.8 on 2025-11-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='artwork',
            field=models.ImageField(blank=True, help_text='Upload artwork image', null=True, upload_to='artwork/'),
        ),
        migrations.AlterField(
            model_name='release',
            name='artwork_url',
            field=models.URLField(blank=True, help_text='Or provide URL to artwork image', null=True),
        ),
    ]
