# Generated by Django 5.2.8 on 2025-11-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_release_artwork_alter_release_artwork_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='photo',
            field=models.ImageField(blank=True, help_text='Concert photo', null=True, upload_to='concerts/'),
        ),
        migrations.AddField(
            model_name='concert',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Or provide URL to concert photo', null=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='setlist',
            field=models.TextField(blank=True, help_text='Setlist for the show', null=True),
        ),
    ]
