# Generated by Django 5.2.8 on 2025-11-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_concert_photo_concert_photo_url_concert_setlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Band photo', upload_to='band_photos/')),
                ('photo_url', models.URLField(blank=True, help_text='Or provide URL to photo', null=True)),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('is_hero', models.BooleanField(default=False, help_text='Use as hero image on home page')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'ordering': ['-is_hero', 'order'],
            },
        ),
    ]
