# Generated by Django 5.2.8 on 2025-11-16 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_bandphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='photo',
            field=models.ImageField(blank=True, help_text='Main concert photo', null=True, upload_to='concerts/'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Or provide URL to main concert photo', null=True),
        ),
        migrations.CreateModel(
            name='ConcertPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Concert photo', upload_to='concerts/')),
                ('photo_url', models.URLField(blank=True, help_text='Or provide URL to photo', null=True)),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='base.concert')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
