# Generated by Django 5.2.8 on 2025-11-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_concert_photo_alter_concert_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandphoto',
            name='is_music_header',
            field=models.BooleanField(default=False, help_text='Use as header image on music page'),
        ),
        migrations.AddField(
            model_name='bandphoto',
            name='is_shows_header',
            field=models.BooleanField(default=False, help_text='Use as header image on shows page'),
        ),
    ]
