# Generated by Django 5.2.8 on 2025-11-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_bandphoto_is_music_header_bandphoto_is_shows_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Merch photo', upload_to='merch/')),
                ('photo_url', models.URLField(blank=True, help_text='Or provide URL to photo', null=True)),
                ('caption', models.CharField(blank=True, help_text='Product name or description', max_length=200, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
